class DatabaseError(Exception): ...
class UniqueUsernameError(DatabaseError): ...
class UniqueEmailError(DatabaseError): ...
class ActivateUserError(DatabaseError): ...
class UserNotExistsError(DatabaseError): ...
class InvalidCredentialsError(DatabaseError): ...
class UserNotFoundError(DatabaseError): ...
